### ISSUE TITLE
Switch to stable MongoDB crate

### ISSUE THREAD

**Issue by PhotonQuantum** [suisei-cn/stargazer-reborn#16]
The change stream feature only exists in git repository now. Switch to the crates.io version once a new MongoDB version is released.

**Comment by George-Miao** [comment]
Temporarily using this patch to solve #46.

```rust
[patch.crates-io]
bson  = { git = "https://github.com/mongodb/bson-rust.git", branch = "2.2.x" }
```

Once another stable version is released, this can be lifted.
