### ISSUE TITLE
Switch from bincode to json

### ISSUE THREAD

**Issue by PhotonQuantum** [suisei-cn/stargazer-reborn#25]
Bincode is a schemaful format. However, our `Value` depends on the format itself to provide type info. We may migrate to json. And we may use serde_json::Value instead of our hand-made format.

**Comment by PhotonQuantum** [comment]
@George-Miao What's your thought? Should we migrate to json and replace our `Value` with `serde_json::Value`?

**Comment by George-Miao** [comment]
> @George-Miao What's your thought? Should we migrate to json and replace our `Value` with `serde_json::Value`?

If that is possible, always consider using a mature crate first.

**Comment by PhotonQuantum** [comment]
Closed by #23 .
