### ISSUE TITLE
Anyway to distinguish `User` from a person in group and a private chat?

### ISSUE THREAD

**Issue by George-Miao** [suisei-cn/stargazer-reborn#27]
Is this possible? Or we can add a property like `type`?

**Comment by PhotonQuantum** [comment]
Or we may see a group as a "User"? Anywa a group has a unique id and its own avatar, and only admin can open its setting page. I'd see an admin as "representing the group" rather than "someone in a group".

**Comment by George-Miao** [comment]
> 

That makes sense.
