### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by George-Miao** [suisei-cn/stargazer-reborn#30]
# API Design
API will be in an RPC-like manner. It is used both for bot and frontend.

## Terminology

`Entity` - Represent a VTB
`session` - A session that is valid in a period of time for users to update their settings and subscriptions, used to interact with API

## Request

A `Request` is a method invocatio. Methods are in URL, and params are serialized into json and sent via request body. 

## Response

Data transferred from server to client.

```rust
struct Response<T> {
  success: bool,
  time: u64 // UNIX timestamp
  data: T,
}
```	

### General methods

- `getUser(user_id)` - Get user information
- `delUser(user_id)` - User chooses to remove their account
- `getEntities()` - Get a table of all entities that can be subscribed
- `newSession()` - Create a new session
- ~`checkSession(session_id)` - Check if a `session_id` is valid~
- `authMe` - Check if a token is valid and corresponds to specified `user_id`  
- ~`getSettings(session_id)` - Get settings of an `User`~
- `updateSetting(session_id, setting)` - Update settings of an `User`
- ~`getSubscription(session_id)` - Get subscription table of an `User`~
- ~`updateSubscription(session_id)` - Update entities table of an `User`~
- `{new, get, update, del}Entity(entity)` - CRUD an `Entity`, **Admin only**
- `getUserIndex()` - Used to get an `Index`, which is discussed [here](https://github.com/suisei-cn/stargazer-reborn/issues/29#issuecomment-1058383924)

## Transportation

All API calls will be transferred through the HTTP Post method, request info are encoded into JSON as HTTP body.

##

**Comment by George-Miao** [comment]
Also, should we include an admin API, to add new entity (VTB) and such?

**Comment by PhotonQuantum** [comment]
> Also, should we include an admin API, to add new entity (VTB) and such?

Yup. A simple webui should work.
