### ISSUE TITLE
Inconsistency of `uuid::Uuid` and `bson::Uuid`

### ISSUE THREAD

**Issue by George-Miao** [suisei-cn/stargazer-reborn#43]
Currently, there are two UUID types:

- One from crate `uuid`
- One from crate `bson`

, where `bson::Uuid` is a wrapper on `uuid v4`, provides binary compatibility for serializing and deserializing function to bson, and thus interactable with MongoDB.

Our core types are all defined with bson uuid, where API interfaces should be using bare uuid types. However, several API methods return core types directly, which includes bson uuid as a field. Normally, this will not cause any problem since besides serializing into bson, `bson::Uuid` has the same behavior as `uuid::Uuid`. But API crate will also be used as an SDK for interacting with the API. Now on the clientside, some of the methods return `bson::Uuid` and others return `uuid::Uuid` which is confusing and inconsistent. We will need a solution for this. Temporarily, I have changed all return types of API to use `bson::Uuid`.

**Comment by PhotonQuantum** [comment]
I was against this idea before because I thought changing uuid type to the bson one might cause problems when interacting with third-party crates. 

It turns out now that this is not the case. So it's okay for me to use `bson::Uuid` directly throughout the project.

**Comment by George-Miao** [comment]
> I was against this idea before because I thought changing uuid type to the bson one might cause problems when interacting with third-party crates.
> 
> It turns out now that this is not the case. So it's okay for me to use `bson::Uuid` directly throughout the project.

Great. That's what im thinking. Then I can close this issue now.
